small-scale: 0.02
sleep-duration-seconds: 60

buttons:
  sit: "H"
  lie: "G"
  sit-on-small: "Z"
  escape-shoe: "X"
  escape-blanket: "B"

sleep-poses:
  - "Калачиком у большого"
  - "Сверху на животе"
  - "Спина к спине"
  - "В обнимку"
  - "Ложкой"
  - "Звёздочка"
  - "Спрятав лицо в груди"
  - "Обняв ногу"
  - "Клубочком у живота"

animations:
  - "Погладить по голове"
  - "Пощекотать"
  - "Покружить"
  - "Подбросить"
  - "Укачивать"
  - "Поцеловать в губы"

carry-poses:
  - "На голове"
  - "В кармане"
  - "На плече"
  - "На руках"
  - "Под одеждой"
  - "У ног"
  - "За спиной"

messages:
  became-small: "§a✨ Ты уменьшился до 3 пикселей! ✨"
  became-normal: "§c📏 Ты вернул нормальный размер"
  now-sitting: "§e💺 Ты сел"
  now-lying: "§7🛌 Ты лёг"
  picked-up: "§6🤲 Ты поднял {player}"
  was-picked-up: "§6🫂 Тебя поднял {player}"
  dropped: "§c📌 Тебя опустили на землю"
  shoved-in-shoe: "§7👟 {big} засунул {small} в кроссовок!"
  escaped-shoe: "§a👟 Ты вылез из кроссовка!"
  under-blanket: "§b🛏️ Вы под одеялом!"
  blanket-escape: "§a🏃‍♂️ Ты вылез из-под одеяла!"
  sitting-on: "§d💺 {big} сел на {small}!"
  crushed: "§c💨 {big} прижал {small}!"
  already-sleeping: "§c❌ В этой кровати уже кто-то спит!"
  wrong-partner: "§c❌ Спать вместе могут только большой и маленький игрок!"
  morning: "§a🌅 Вы выспались! Доброе утро!"
