small-scale: 0.35
sleep-duration-seconds: 60

messages:
  became-small: "§a✨ Ты уменьшился до 3 пикселей! ✨"
  became-normal: "§c📏 Ты вернул нормальный размер"
  carried: "§6🤲 Ты взял на руки {player}"
  was-carried: "§6🫂 Тебя взял на руки {player}"
  dropped: "§c📌 Тебя опустили на землю"
  in-pocket: "§e👖 Тебя положили в карман! Используй /unsmoll чтобы вылезти"
  in-shoe: "§7👟 Тебя засунули в кроссовок! Используй /unsmoll чтобы вылезти"
  sitting: "§e💺 Ты сел"
  lying: "§7🛌 Ты лёг"
  under-blanket: "§b🛏️ Вы под одеялом!"
  morning: "§a🌅 Доброе утро!"
